### ISSUE TITLE
signing and build-compare

### ISSUE THREAD

**Issue by olafhering** [openSUSE/obs-build#168]
Not sure if I already reported a bugzilla bug, in any case:

build-compare has to compare old signed package and new signed package. But right now the process compares just old signed package and new not-yet-signed package. This is a bug in the buildservice, not in build-compare. As a second step build-compare MAY need an update to interpret the sign.

https://bugzilla.suse.com/show_bug.cgi?id=906160

**Comment by adrianschroeter** [comment]
This is wanted / a design decision. Otherwise it would mean that we have to re-setup every build env which would increase the build load a lot.

Also, I see no reason why build-compare should take care about signature. It's job is to decide if content differs, not the origin of the package.

**Comment by olafhering** [comment]
Have you read what I wrote, and looked at build logs? I assume you happen to know how build-compare works.

Just run build-compare at the very end of the second cycle when the new package is signed. Only then the included binaries will be similar to the previous build. And the binary signature is likely part of the decision if a given package is identical to the former build. Since its only available in the second cycle build-compare has no way to compare old and new signature.

But if its ok that build-compare throws away the signature and compares just the unsigned binaries thats fine with me.

**Comment by adrianschroeter** [comment]
sure, it is fine to ignore the signature. And since the rpm archives has been already created it is fine when build-compare is unpacking and stripping the signatures. 

We should really avoid more and more special code in OBS just for kernel packages. Also when the decision to consider the built rpms as identical enough happens in first stage, we avoid to re-setup the second build env just for signing. And it reduces the load on the signer a lot, kernel packages tend to block it  for quite some time these days.
