### ISSUE TITLE
Network support for kvm

### ISSUE THREAD

**Issue by Gyeongmin** [openSUSE/obs-build#176]
Virtualization of kvm can not use network
However, when build a commercial program, connect license server to get certification during the build

Are there any particular reason why you do not support the network kvm?

**Comment by mlschroe** [comment]
Yes, we want reproducible builds that don't rely on some outside resource.

**Comment by adrianschroeter** [comment]
IMHO it would be fine to implement special sandbox modes like "kvm-network" which allow access to the network. The OBS admin of an instance may allow to build inside of such an instance, but we won't allow it by default. And not at all on public instances like build.opensuse.org, since it can also be abused to attack external networks.
