### ISSUE TITLE
Contents of the rpm package leak into its build.

### ISSUE THREAD

**Issue by simotek** [openSUSE/obs-build#476]
I found this testing an rpm build with a bug that causes a deadlock.

The only difference between the 2 packages is that package 2 the "passing" package has patch 1008 on line 252 commented out (I'm 99% sure the patch causes a deadlock). The failing package deadlocks on a call to rpm -qf in the post-build-checks, given that there has never been a successful build of the failed package the only way this can be happening is if the rpm package being built is being leaked back into the buildroot somehow, having looked through the rpm spec file I can't see anything obvious there. 

1. https://build.opensuse.org/package/show/home:simotek:rpm-obs-fail/rpm
2. https://build.opensuse.org/package/show/home:simotek:rpm-obs-pass/rpm

**Comment by Conan-Kudo** [comment]
This is happening because OBS' `post-build-checks` installs the package first before running the other checks. Obviously, no one thought that a bad rpm package could actually break this, but this is the one case where this design fails.

This mainly appears to expose a bug in that patch, more than anything else...

**Comment by mlschroe** [comment]
Right, thanks Conan-Kudo for the explanation. Closing this issue.
