### ISSUE TITLE
ARG in Dockerfile are not processed for zypper calls

### ISSUE THREAD

**Issue by fcrozat** [openSUSE/obs-build#679]
```
ARG BASE
FROM $BASE
ARG VERSION

RUN zypper in -y python3$VERSION-base python3$VERSION-pip python3$VERSION-setuptools python3$VERSION-wheel
```
VERSION is set using prjconfig but it not expanded when container is built (see https://build.opensuse.org/package/show/home:fcrozat:opensuse-devstacks/python-3.6-devel for the entire example)

The same code is building fine locally when using podman

**Comment by mlschroe** [comment]
Your project config only defines $VERSION for the containers_tw repo. And it does not define $RELEASE_PACKAGE at all (because of the missing `dockerarg:` prefix). So I'm not sure if this is a valid issue or not.

**Comment by fcrozat** [comment]
for VERSION, it is wanted: this is because on TW, python 3.6 is named python36 but not on Leap nor SLE (and I4m trying to create unified Dockerfile for all platforms). 

For RELEASE_PACKAGE, indeed, I missed dockerarg was needed for each argument. Fixed in prjconfig now.

**Comment by fcrozat** [comment]
It is also visible on SLE builds at https://build.suse.de/project/show/home:fcrozat:suse-devstacks

**Comment by mlschroe** [comment]
That's caused by something different: we currently do not take the docker arg buildflags into account when checking if packages dependencies need to be recalculated again. So the schedulers had the old dependencies in the cache and your changes to the docker args were ignored. I manually triggered a re-evaluation of the dependencies and now the deps are correct. (A source change would also have worked.)

Anyway, I'll change the code to look out for dockerarg changes as well.

So, is there anything else to fix?

**Comment by mlschroe** [comment]
https://github.com/openSUSE/open-build-service/pull/10938

**Comment by fcrozat** [comment]
So far, everything looks good regarding ARG handling. Let's close. Thanks a lot !
